services:
  articles.hosts.api:
    image: articles.hosts.api
    build:
      context: .
      dockerfile: src/Articles/Hosts/Articles.Hosts.Api/Dockerfile
    ports:
      - "5001:8080"
    networks:
      - articles
      
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    networks:
      - articles

volumes:
  postgres_data:

networks:
  articles-network:
